# Site settings
title: SDR for Engineers
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Software Defined Radio for Engineers
user_description: A practical guide to the wireless phyiscal layer<br> The objective of this book is to provide a hands-on learning experience using SDR for engineering students and industry practitioners who are interested in mastering the design, implementation, and experimentation of a communication system.
user_title: A practical guide to the wireless physical layer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username: sdrforengineers
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
